import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarInset, SidebarTrigger } from "@/components/ui/sidebar";
import { AlbumProvider } from "@/contexts/AlbumContext";
import { PlayerProvider } from "@/contexts/PlayerContext";
import { BottomPlayer } from "@/components/bottom-player";
import { BCSidebar } from "@/components/bc-sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AlbumProvider>
          <PlayerProvider>
            <SidebarProvider>
              <BCSidebar />
              <SidebarInset>
                <header className="flex h-16 shrink-0 items-center gap-2 px-4 border-b">
                  <SidebarTrigger className="-ml-1" />
                </header>
                <div className="flex-1 pb-24"> {/* Add padding bottom for the bottom player */}
                  {children}
                </div>
              </SidebarInset>
              <BottomPlayer />
            </SidebarProvider>
          </PlayerProvider>
        </AlbumProvider>
      </body>
    </html>
  );
}
